FROM 84codes/crystal:1.13.2-ubuntu-noble

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libgmp-dev \
    libc6-dev \
    libpcre3-dev \
    libpcre2-dev \
    libxml2-dev \
    libssl-dev \
    tzdata \
    zlib1g-dev \
    xz-utils \
    make \
    git \
    autoconf \
    automake \
    libtool \
    patch \
    libssh2-1-dev \
    curl \
    docker.io \
    zsh \
    bash \
    passwd \
    g++ \
    openssl \
    libyaml-dev \
    openssh-client && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
  && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

SHELL ["/bin/zsh", "-c"]

RUN echo '/bin/zsh' | chsh `whoami`

RUN rm /root/.zshrc && ln -s /home/app/asset-sniper/.zshrc /root/.zshrc

ENV DEVCONTAINER=true

ENTRYPOINT []

CMD ["tail", "-f", "/dev/null"]
