FROM crystallang/crystal:1.13-alpine

RUN apk update \
  && apk add --update --no-cache gcc gmp-dev libevent-static musl-dev pcre-dev pcre2-dev libxml2-dev \
    libxml2-static openssl-dev openssl-libs-static tzdata yaml-static zlib-static xz-static \
    make git autoconf automake libtool patch libssh2-static libssh2-dev \
    curl docker zsh bash openssl shadow \
    gcc g++ libc-dev libxml2-dev openssl-dev yaml-dev zlib-dev openssh-client

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
  && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

SHELL ["/bin/zsh", "-c"]

RUN echo '/bin/zsh' | chsh `whoami`

RUN rm /root/.zshrc && ln -s /home/app/asset-sniper/.zshrc /root/.zshrc

ENV DEVCONTAINER=true

CMD ["tail", "-f", "/dev/null"]
